package com.lunivore.hellbound

import com.lunivore.hellbound.glue.Scenario
import org.junit.Test

class CanPlayTheGame : Scenario() {

    @Test
    fun `The grid should start empty`() {
        Given_a_game.that_is_new()
        Then_the_grid.should_look_like("""
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            """)
    }

    @Test
    fun `Pressing a key should start the game`() {
        Given_a_game.that_is_new()
        When_the_player.presses_any_key()
        Then_the_grid.should_look_like("""
            ....XXX....
            .....X.....
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            """)
    }

    @Test
    fun `ASDQE should move and rotate the shape`() {
        Given_a_game.thats_just_started()
        When_the_player.presses_the_sequence("DE")
        Then_the_grid.should_look_like("""
            ......X....
            .....XX....
            ......X....
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            ...........
            """)
    }


}
